spring:
  application:
    name: kanban
  datasource:
    # url: jdbc:h2:mem:kanbandb
    url: jdbc:h2:./h2db/kanbandb
    username: admin
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # 起動時に自動生成（create-drop）/ 更新（update）
      ddl-auto: update
    # 実行されるSQLをコンソールに表示
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: ${JWT_SECRET}
    # トークンの有効期限（１時間）
    expiration-ms: 3600000